{% set name = "ngram" %}
{% set version = "1.3.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.openfst.org/twiki/pub/GRM/NGramDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 0b984c60d37eb786a8f54ebdd2c5cf87cc207c5d86a43db789fa9758f816ca1c
  patches:
    - patches/0001-Add-CMake-files.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make                    # [unix]
    - gnuconfig               # [unix]
    - cmake                   # [win]
    - ninja                   # [win]
    - m2-patch                # [win]
  host:
    - openfst ==1.8.3
    - dlfcn-win32             # [win]
  run:
    - openfst ==1.8.3
    - ucrt                    # [win]


{% set ngram_binaries = [
    "ngramapply", "ngramcontext", "ngramcount", "ngraminfo", "ngrammake", "ngrammarginalize", "ngrammerge",
    "ngramperplexity", "ngramprint", "ngramrandgen", "ngramread", "ngramshrink", "ngramsort", "ngramsplit",
    "ngramsymbols", "ngramtransfer"
] %}

test:
  commands:
    # binaries:
    {% for each_bin in ngram_binaries %}
      # If behaving properly these will have return code 1.
    - {{ each_bin }} --helpshort >/dev/null || [[ $? == 1 ]]       # [unix]
    - {{ each_bin }} --helpshort & if errorlevel 1 ( exit /b 0)    # [win]
    {% endfor %}

about:
  home: http://ngram.opengrm.org
  license: Apache-2.0
  license_file: LICENSE
  summary: N-Gram modeling
  description: |
    A library for making and modifying n-gram language models encoded as weighted finite-state transducers (FSTs).
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/NGramQuickTour

extra:
  recipe-maintainers:
    - kylebgorman
    - mmcauliffe
